<!DOCTYPE html><html dir="rtl"><head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1256">
<meta http-equiv="Content-Language" content="ar-ye">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="css/style.css">
<link rel="stylesheet" href="css/bootstrap.css">
<title>الحالة</title>
 <script language="JavaScript1.2">

function reapply(){
setTimeout("slideit()",2000);
return true;
}
window.onerror=reapply;
</script><style type="text/css">* {user-select: auto !important; -webkit-user-select: auto !important;}</style><input type="hidden" id="inject_idm_text_selection">
<script language="JavaScript1.1">
<!--
var image1=new Image();
image1.src="images/ads1.gif";        // ضع هنا عنوان الصورة الأولى
var image2=new Image();    
image2.src="images/ads1.gif";        // عنوان الصورة الثانية
var image3=new Image();
image3.src="images/ads1.gif";        // عنوان الصورة الثالثة
//-->
</script>

<script language="JavaScript">
<!--

    function openLogout() {
	if (window.name != 'hotspot_status') return true;
        open('http://www.a.com/logout', 'hotspot_logout', 'toolbar=0,location=0,directories=0,status=0,menubars=0,resizable=1,width=280,height=250');
	window.close();
	return false;
    }
//-->
</script>

</head>

<body onload="slideit()" id="animate-area">


<div id="logo">شــبــكـــة المدينة نت اللاسلكية<div class="info"><h4>للتواصل والاستفسار : 777441276  </h4></div></div>



<div id="content">
<div align="center" class="box"><form action="http://www.a.com/logout" name="logout" onsubmit="return openLogout()" class="form-signin">
<br><div style="text-align: center;"><strong>الرصيد المتبقي هو 747.4 MiB !</strong></div><br><table border="1" class="tabula">


          
	

	
	<tbody><tr><td align="right">الوقت المتبقي:</td><td class="style1"> 13h43m18s</td></tr>

	<tr><td align="right">التحميل المتبقي:</td><td class="style1">747.4 MiB</td></tr>



</tbody></table>

<br>
<!-- user manager link
<button onclick="document.location='http://www.a.com/user?subs='">status</button>
<!-- end of user manager link -->
<center>
<table border="0" cellpadding="2" width="100%" dir="rtl" cellspacing="4">
	<tbody><tr>
		<td><a title="قوقل" href="https://www.google.com">
		<img border="0" src="images/dribbble-b.png" width="50" height="59"></a></td>
		<td><a title="فيسبوك" href="https://www.facebook.com">
		<img border="0" src="images/facebook-b.png" width="50" height="59"></a></td>
		<td><a title="تويتر" href="https://www.twitter.com">
		<img border="0" src="images/twitter-b.png" width="50" height="59"></a></td>
		<td><a title="صفحات كشكول" href="http://www.kashkol.info">
	</a></td></tr>
	<tr>
		<td><a href="https://www.google.com">جوجل</a></td>
		<td><a href="https://www.facebook.com">فيسبوك</a></td>
		<td><a href="https://www.twitter.com">تويتر</a></td>
	</tr>
</tbody></table>
</center><p></p><input class="btn btn-lg btn-primary btn-block" type="submit" value="تسجيل الخروج">

</form>

</div>




<br>
<div class="animate-area"></div>
<br><input class="btn btn-lg btn-primary btn-block" type="submit" value="برمجة وتركيب اي تك 713570844">
<!-- div align="center" id="footer"></div>

</body>

</html>
--></div></body></html>
